version: "3.7"
services:
  api:
    image: krisyslimited/harpoon:1.4
    restart: always
    links:
      - db:db
    ports:
      - 5000:5000
    depends_on: 
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - HARPOON_DB_HST=db
      - HARPOON_DB_PWD=''
  svc:
    image: krisyslimited/reader:1.0
    links:
      - db:db
    depends_on:
      - db
    environment:
      - O8DBHOST=db
      - MSSQLPWD=''
  db:
    image: krisyslimited/sex:latest
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=''
    volumes:
      - /root/data:/var/opt/mssql