apiVersion: apps/v1
kind: Deployment
metadata:
  name: harpoon-deployment
  labels:
    app: harpoon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harpoon
  template:
    metadata:
      labels:
        app: harpoon
    spec:
      containers:
      - name: harpoon
        image: krisyslimited/harpoon:latest
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: HARPOON_DB_DB
          value: "stocks"
        - name: HARPOON_DB_HST
          value: "mssql-service"
        - name: HARPOON_DB_PRT
          value: "1433"
        - name: HARPOON_DB_USR
          value: "sa"
        - name: HARPOON_DB_PWD
          value: "Password77"
      imagePullSecrets:
      - name: docker-hub-cred
---
apiVersion: v1
kind: Service
metadata:
  name: harpoon-service
spec:
  type: LoadBalancer
  selector:
    app: harpoon
  ports:
    - name: tcpapi
      protocol: TCP
      port: 5000
      targetPort: 5000