apiVersion: apps/v1
kind: Deployment
metadata:
  name: harpoon-deployment
  labels:
    app: harpoon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harpoon
  template:
    metadata:
      labels:
        app: harpoon
    spec:
      containers:
      - name: harpoon
        image: krisyslimited/harpoon:1.4
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: HARPOON_DB_HST
          value: "mssql-service"
        - name: HARPOON_DB_PWD
          valueFrom:
            secretKeyRef:
              name: shillings-db-secret
              key: password
      imagePullSecrets:
      - name: docker-hub-cred
---
apiVersion: v1
kind: Service
metadata:
  name: harpoon-service
spec:
  type: ClusterIP
  selector:
    app: harpoon
  ports:
    - name: httpapi
      protocol: TCP
      port: 5000
      targetPort: 5000