
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shillings-ingress
spec:
  rules:
    - host: shillings.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shillings-service
                port: 
                  number: 80