DECLARE @dividends XML = '<companies>
    <code>138SL</code>
    <security>138 STUDENT LIVING JAMAICA LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>414500000</outstandingShares>
    <marketCapitalization>2174920048.5</marketCapitalization>
</companies>
<companies>
    <code>138SLVR</code>
    <security>138 STUDENT LIVING JAMAICA LIMITED VARIABLE PREFERENCE</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>34528500</outstandingShares>
    <marketCapitalization>258963750</marketCapitalization>
</companies>
<companies>
    <code>1834</code>
    <security>1834 INVESTMENTS LIMITED</security>
    <currency>JMD</currency>
    <industry>COMMUNICATIONS</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1211243827</outstandingShares>
    <marketCapitalization>994353662.36</marketCapitalization>
    <dividends>
        <code>1834</code>
        <recordDate>2020-11-24</recordDate>
        <paymentDate>2020-12-11</paymentDate>
        <currency>JMD</currency>
        <amount>0.04</amount>
    </dividends>
</companies>
<companies>
    <code>BIL</code>
    <security>BARITA INVESTMENTS LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1220388243</outstandingShares>
    <marketCapitalization>109769657200.94</marketCapitalization>
    <dividends>
        <code>BIL</code>
        <recordDate>2021-09-23</recordDate>
        <paymentDate>2021-10-07</paymentDate>
        <currency>JMD</currency>
        <amount>3.029</amount>
    </dividends>
    <dividends>
        <code>BIL</code>
        <recordDate>2021-02-05</recordDate>
        <paymentDate>2021-02-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.746</amount>
    </dividends>
    <dividends>
        <code>BIL</code>
        <recordDate>2020-09-22</recordDate>
        <paymentDate>2020-10-07</paymentDate>
        <currency>JMD</currency>
        <amount>2.216</amount>
    </dividends>
</companies>
<companies>
    <code>BRG</code>
    <security>BERGER PAINTS JAMAICA LTD.</security>
    <currency>JMD</currency>
    <industry>MANUFACTURING</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>214322393</outstandingShares>
    <marketCapitalization>2786191109</marketCapitalization>
</companies>
<companies>
    <code>CCC</code>
    <security>CARIBBEAN CEMENT COMPANY LTD.</security>
    <currency>JMD</currency>
    <industry>MANUFACTURING</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>851136591</outstandingShares>
    <marketCapitalization>61113276312.66</marketCapitalization>
</companies>
<companies>
    <code>CPJ</code>
    <security>CARIBBEAN PRODUCERS JAMAICA LIMITED</security>
    <currency>JMD</currency>
    <industry>RETAIL</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1100000000</outstandingShares>
    <marketCapitalization>17135142200</marketCapitalization>
</companies>
<companies>
    <code>CAR</code>
    <security>CARRERAS LIMITED</security>
    <currency>JMD</currency>
    <industry>RETAIL</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>4854400000</outstandingShares>
    <marketCapitalization>39937095401.6</marketCapitalization>
    <dividends>
        <code>CAR</code>
        <recordDate>2022-03-04</recordDate>
        <paymentDate>2022-03-24</paymentDate>
        <currency>JMD</currency>
        <amount>0.23</amount>
    </dividends>
    <dividends>
        <code>CAR</code>
        <recordDate>2021-12-13</recordDate>
        <paymentDate>2021-12-30</paymentDate>
        <currency>JMD</currency>
        <amount>0.21</amount>
    </dividends>
    <dividends>
        <code>CAR</code>
        <recordDate>2021-08-05</recordDate>
        <paymentDate>2021-08-25</paymentDate>
        <currency>JMD</currency>
        <amount>0.16</amount>
    </dividends>
    <dividends>
        <code>CAR</code>
        <recordDate>2021-06-07</recordDate>
        <paymentDate>2021-06-23</paymentDate>
        <currency>JMD</currency>
        <amount>0.25</amount>
    </dividends>
    <dividends>
        <code>CAR</code>
        <recordDate>2021-03-01</recordDate>
        <paymentDate>2021-03-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.21</amount>
    </dividends>
    <dividends>
        <code>CAR</code>
        <recordDate>2020-11-23</recordDate>
        <paymentDate>2020-12-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.17</amount>
    </dividends>
</companies>
<companies>
    <code>CBNY</code>
    <security>CIBONEY GROUP LIMITED</security>
    <currency>JMD</currency>
    <industry>TOURISM</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>546000000</outstandingShares>
    <marketCapitalization>413582442</marketCapitalization>
</companies>
<companies>
    <code>CWJDEFERREDA</code>
    <security>COMMUNITY &amp; WORKERS OF JAMAICA CCU DEFFERED SHARE</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>450000000</outstandingShares>
    <marketCapitalization>805673250</marketCapitalization>
</companies>
<companies>
    <code>EPLY7.50</code>
    <security>EPPLEY 7.50% PREF SHARES DUE 2024</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>83334000</outstandingShares>
    <marketCapitalization>500004000</marketCapitalization>
</companies>
<companies>
    <code>CPFV</code>
    <security>EPPLEY CARIBBEAN PROPERTY FUND LIMITED SCC</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>136499203</outstandingShares>
    <marketCapitalization>5192176476.1</marketCapitalization>
    <dividends>
        <code>CPFV</code>
        <recordDate>2021-12-20</recordDate>
        <paymentDate>2022-02-21</paymentDate>
        <currency>BBD</currency>
        <amount>0.016</amount>
    </dividends>
    <dividends>
        <code>CPFV</code>
        <recordDate>2021-05-28</recordDate>
        <paymentDate>2021-07-09</paymentDate>
        <currency>BBD</currency>
        <amount>0.008</amount>
    </dividends>
</companies>
<companies>
    <code>EPLY</code>
    <security>EPPLEY LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>192468300</outstandingShares>
    <marketCapitalization>7782211660.7</marketCapitalization>
    <dividends>
        <code>EPLY</code>
        <recordDate>2021-11-30</recordDate>
        <paymentDate>2021-12-17</paymentDate>
        <currency>JMD</currency>
        <amount>0.0372</amount>
    </dividends>
    <dividends>
        <code>EPLY</code>
        <recordDate>2021-08-31</recordDate>
        <paymentDate>2021-09-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.0372</amount>
    </dividends>
    <dividends>
        <code>EPLY</code>
        <recordDate>2021-05-28</recordDate>
        <paymentDate>2021-06-11</paymentDate>
        <currency>JMD</currency>
        <amount>0.0372</amount>
    </dividends>
    <dividends>
        <code>EPLY</code>
        <recordDate>2021-04-06</recordDate>
        <paymentDate>2021-04-23</paymentDate>
        <currency>JMD</currency>
        <amount>0.83</amount>
    </dividends>
    <dividends>
        <code>EPLY</code>
        <recordDate>2020-11-30</recordDate>
        <paymentDate>2020-12-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.0372</amount>
    </dividends>
</companies>
<companies>
    <code>EPLY5</code>
    <security>EPPLEY LIMITED 5% PREFERENCE SHARES</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>15000000</outstandingShares>
    <marketCapitalization>330000000</marketCapitalization>
</companies>
<companies>
    <code>EPLY7.25</code>
    <security>EPPLEY LIMITED 7.25% PREFERENCE SHARES</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>30000000</outstandingShares>
    <marketCapitalization>600000000</marketCapitalization>
</companies>
<companies>
    <code>EPLY7.75</code>
    <security>EPPLEY LIMITED 7.75% PREFERENCE SHARES</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>26667100</outstandingShares>
    <marketCapitalization>549342260</marketCapitalization>
</companies>
<companies>
    <code>FIRSTROCKJMD</code>
    <security>FIRST ROCK CAPITAL HOLDINGS LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>38253000</outstandingShares>
    <marketCapitalization>455461486.67</marketCapitalization>
    <dividends>
        <code>FIRSTROCKJMD</code>
        <recordDate>2021-12-03</recordDate>
        <paymentDate>2021-12-17</paymentDate>
        <currency>USD</currency>
        <amount>0.0007</amount>
    </dividends>
    <dividends>
        <code>FIRSTROCKJMD</code>
        <recordDate>2021-06-03</recordDate>
        <paymentDate>2021-06-11</paymentDate>
        <currency>USD</currency>
        <amount>0.0006</amount>
    </dividends>
    <dividends>
        <code>FIRSTROCKJMD</code>
        <recordDate>2020-12-29</recordDate>
        <paymentDate>2021-01-11</paymentDate>
        <currency>USD</currency>
        <amount>0.0012</amount>
    </dividends>
    <dividends>
        <code>FIRSTROCKJMD</code>
        <recordDate>2020-09-25</recordDate>
        <paymentDate>2020-09-30</paymentDate>
        <currency>USD</currency>
        <amount>0.0008</amount>
    </dividends>
</companies>
<companies>
    <code>GK</code>
    <security>GRACEKENNEDY LIMITED</security>
    <currency>JMD</currency>
    <industry>CONGLOMERATES</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>995069405</outstandingShares>
    <marketCapitalization>102651762822.91</marketCapitalization>
    <dividends>
        <code>GK</code>
        <recordDate>2021-11-26</recordDate>
        <paymentDate>2021-12-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.55</amount>
    </dividends>
    <dividends>
        <code>GK</code>
        <recordDate>2021-09-03</recordDate>
        <paymentDate>2021-09-24</paymentDate>
        <currency>JMD</currency>
        <amount>0.48</amount>
    </dividends>
    <dividends>
        <code>GK</code>
        <recordDate>2021-05-28</recordDate>
        <paymentDate>2021-06-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.45</amount>
    </dividends>
    <dividends>
        <code>GK</code>
        <recordDate>2021-03-15</recordDate>
        <paymentDate>2021-04-06</paymentDate>
        <currency>JMD</currency>
        <amount>0.45</amount>
    </dividends>
    <dividends>
        <code>GK</code>
        <recordDate>2020-11-23</recordDate>
        <paymentDate>2020-12-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.55</amount>
    </dividends>
</companies>
<companies>
    <code>GHL</code>
    <security>GUARDIAN HOLDINGS LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>232024923</outstandingShares>
    <marketCapitalization>127673201856.58</marketCapitalization>
    <dividends>
        <code>GHL</code>
        <recordDate>2021-08-12</recordDate>
        <paymentDate>2021-08-30</paymentDate>
        <currency>TTD</currency>
        <amount>0.18</amount>
    </dividends>
</companies>
<companies>
    <code>JBG</code>
    <security>JAMAICA BROILERS GROUP</security>
    <currency>JMD</currency>
    <industry>MANUFACTURING</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1199276400</outstandingShares>
    <marketCapitalization>35400950746.83</marketCapitalization>
    <dividends>
        <code>JBG</code>
        <recordDate>2022-03-11</recordDate>
        <paymentDate>2022-04-14</paymentDate>
        <currency>JMD</currency>
        <amount>0.31</amount>
    </dividends>
    <dividends>
        <code>JBG</code>
        <recordDate>2021-11-10</recordDate>
        <paymentDate>2021-11-30</paymentDate>
        <currency>JMD</currency>
        <amount>0.15</amount>
    </dividends>
    <dividends>
        <code>JBG</code>
        <recordDate>2021-03-10</recordDate>
        <paymentDate>2021-04-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.28</amount>
    </dividends>
    <dividends>
        <code>JBG</code>
        <recordDate>2020-10-09</recordDate>
        <paymentDate>2020-10-29</paymentDate>
        <currency>JMD</currency>
        <amount>0.13</amount>
    </dividends>
</companies>
<companies>
    <code>JP</code>
    <security>JAMAICA PRODUCERS GROUP LTD.</security>
    <currency>JMD</currency>
    <industry>CONGLOMERATES</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1122144036</outstandingShares>
    <marketCapitalization>24201806709.96</marketCapitalization>
    <dividends>
        <code>JP</code>
        <recordDate>2021-12-20</recordDate>
        <paymentDate>2022-01-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.25</amount>
    </dividends>
    <dividends>
        <code>JP</code>
        <recordDate>2020-12-21</recordDate>
        <paymentDate>2021-01-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.2</amount>
    </dividends>
</companies>
<companies>
    <code>JPS5C</code>
    <security>JAMAICA PUBLIC SERVICE 5% C</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>66500</outstandingShares>
    <marketCapitalization>29925</marketCapitalization>
</companies>
<companies>
    <code>JPS5D</code>
    <security>JAMAICA PUBLIC SERVICE 5% D</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>680000</outstandingShares>
    <marketCapitalization>319600</marketCapitalization>
    <dividends>
        <code>JPS5D</code>
        <recordDate>2021-12-15</recordDate>
        <paymentDate>2021-12-31</paymentDate>
        <currency>JMD</currency>
        <amount>0.025</amount>
    </dividends>
    <dividends>
        <code>JPS5D</code>
        <recordDate>2021-09-15</recordDate>
        <paymentDate>2021-10-01</paymentDate>
        <currency>JMD</currency>
        <amount>0.025</amount>
    </dividends>
    <dividends>
        <code>JPS5D</code>
        <recordDate>2021-06-15</recordDate>
        <paymentDate>2021-07-01</paymentDate>
        <currency>JMD</currency>
        <amount>0.025</amount>
    </dividends>
    <dividends>
        <code>JPS5D</code>
        <recordDate>2021-03-15</recordDate>
        <paymentDate>2021-04-01</paymentDate>
        <currency>JMD</currency>
        <amount>0.025</amount>
    </dividends>
    <dividends>
        <code>JPS5D</code>
        <recordDate>2020-12-15</recordDate>
        <paymentDate>2020-12-31</paymentDate>
        <currency>JMD</currency>
        <amount>0.025</amount>
    </dividends>
    <dividends>
        <code>JPS5D</code>
        <recordDate>2020-09-15</recordDate>
        <paymentDate>2020-10-01</paymentDate>
        <currency>JMD</currency>
        <amount>0.025</amount>
    </dividends>
</companies>
<companies>
    <code>JPS5</code>
    <security>JAMAICA PUBLIC SERVICE CO. 5%</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>0</outstandingShares>
    <marketCapitalization>0</marketCapitalization>
</companies>
<companies>
    <code>JPS6</code>
    <security>JAMAICA PUBLIC SERVICE CO. 6%</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>300000</outstandingShares>
    <marketCapitalization>153000</marketCapitalization>
</companies>
<companies>
    <code>JPS9.5</code>
    <security>JAMAICA PUBLIC SERVICE CO. 9.5%</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>2455607</outstandingShares>
    <marketCapitalization>7682194607.01</marketCapitalization>
</companies>
<companies>
    <code>JPS7</code>
    <security>JAMAICA PUBLIC SERVICE CO. LTD. 7%</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>420000</outstandingShares>
    <marketCapitalization>268800</marketCapitalization>
</companies>
<companies>
    <code>JSE</code>
    <security>JAMAICA STOCK EXCHANGE</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>701250000</outstandingShares>
    <marketCapitalization>12474393896.25</marketCapitalization>
    <dividends>
        <code>JSE</code>
        <recordDate>2021-08-09</recordDate>
        <paymentDate>2021-08-23</paymentDate>
        <currency>JMD</currency>
        <amount>0.113</amount>
    </dividends>
    <dividends>
        <code>JSE</code>
        <recordDate>2021-04-06</recordDate>
        <paymentDate>2021-04-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.16</amount>
    </dividends>
</companies>
<companies>
    <code>JMMB7.50</code>
    <security>JMMB 7.5% JMD PREFERENCE SHARES</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>941699000</outstandingShares>
    <marketCapitalization>941699000</marketCapitalization>
</companies>
<companies>
    <code>JMMBGL7.00NC</code>
    <security>JMMB GROUP 7.00% VR JMD CR PREFERENCE SHARES</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>32177000</outstandingShares>
    <marketCapitalization>57918600</marketCapitalization>
</companies>
<companies>
    <code>JMMBGL7.25C</code>
    <security>JMMB GROUP 7.25% VR JMD CR PREFERENCE SHARES</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1848937000</outstandingShares>
    <marketCapitalization>2942259671.53</marketCapitalization>
</companies>
<companies>
    <code>JMMBGL</code>
    <security>JMMB GROUP LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1955552532</outstandingShares>
    <marketCapitalization>80266519985.71</marketCapitalization>
    <dividends>
        <code>JMMBGL</code>
        <recordDate>2021-12-10</recordDate>
        <paymentDate>2022-01-07</paymentDate>
        <currency>JMD</currency>
        <amount>0.25</amount>
    </dividends>
    <dividends>
        <code>JMMBGL</code>
        <recordDate>2021-08-16</recordDate>
        <paymentDate>2021-09-09</paymentDate>
        <currency>JMD</currency>
        <amount>0.6</amount>
    </dividends>
    <dividends>
        <code>JMMBGL</code>
        <recordDate>2020-11-24</recordDate>
        <paymentDate>2020-12-21</paymentDate>
        <currency>JMD</currency>
        <amount>0.25</amount>
    </dividends>
</companies>
<companies>
    <code>JMMBGL7.15</code>
    <security>JMMB GROUP LIMITED 7.15% CUMULATIVE REDEEMABLE PREFERENCE SHARE</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>115493000</outstandingShares>
    <marketCapitalization>343014210</marketCapitalization>
</companies>
<companies>
    <code>JMMBGL7.25</code>
    <security>JMMB GROUP LIMITED 7.25%</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>9434000</outstandingShares>
    <marketCapitalization>25540554.99</marketCapitalization>
</companies>
<companies>
    <code>JMMBGL7.35</code>
    <security>JMMB GROUP LIMITED 7.35% CUMULATIVE REDEEMABLE PREFERENCE SHARE</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>3206485000</outstandingShares>
    <marketCapitalization>10153559206.45</marketCapitalization>
</companies>
<companies>
    <code>JMMBGL7.50</code>
    <security>JMMB GROUP LIMITED 7.50%</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1827548000</outstandingShares>
    <marketCapitalization>1834905708.25</marketCapitalization>
</companies>
<companies>
    <code>KEY</code>
    <security>KEY INSURANCE COMPANY LIMITED</security>
    <currency>JMD</currency>
    <industry>INSURANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>559323101</outstandingShares>
    <marketCapitalization>2404179874.94</marketCapitalization>
</companies>
<companies>
    <code>KPREIT</code>
    <security>KINGSTON PROPERTIES LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>677652928</outstandingShares>
    <marketCapitalization>6427618662.78</marketCapitalization>
    <dividends>
        <code>KPREIT</code>
        <recordDate>2021-07-23</recordDate>
        <paymentDate>2021-08-23</paymentDate>
        <currency>USD</currency>
        <amount>0.0007</amount>
    </dividends>
    <dividends>
        <code>KPREIT</code>
        <recordDate>2021-02-10</recordDate>
        <paymentDate>2021-03-11</paymentDate>
        <currency>USD</currency>
        <amount>0.0007</amount>
    </dividends>
</companies>
<companies>
    <code>KW</code>
    <security>KINGSTON WHARVES LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1430199578</outstandingShares>
    <marketCapitalization>60065642013.61</marketCapitalization>
    <dividends>
        <code>KW</code>
        <recordDate>2021-12-16</recordDate>
        <paymentDate>2022-01-17</paymentDate>
        <currency>JMD</currency>
        <amount>0.37</amount>
    </dividends>
    <dividends>
        <code>KW</code>
        <recordDate>2021-07-21</recordDate>
        <paymentDate>2021-08-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.23</amount>
    </dividends>
    <dividends>
        <code>KW</code>
        <recordDate>2020-12-17</recordDate>
        <paymentDate>2021-01-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.34</amount>
    </dividends>
</companies>
<companies>
    <code>MASSY</code>
    <security>MASSY HOLDINGS LTD</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1979384540</outstandingShares>
    <marketCapitalization>242414419004.29</marketCapitalization>
</companies>
<companies>
    <code>MIL</code>
    <security>MAYBERRY INVESTMENTS LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1201149291</outstandingShares>
    <marketCapitalization>8425631063.77</marketCapitalization>
    <dividends>
        <code>MIL</code>
        <recordDate>2021-12-03</recordDate>
        <paymentDate>2021-12-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.32</amount>
    </dividends>
</companies>
<companies>
    <code>MJE</code>
    <security>MAYBERRY JAMAICAN EQUITIES LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1201149291</outstandingShares>
    <marketCapitalization>9307967706.5</marketCapitalization>
    <dividends>
        <code>MJE</code>
        <recordDate>2021-05-17</recordDate>
        <paymentDate>2021-05-31</paymentDate>
        <currency>JMD</currency>
        <amount>0.06</amount>
    </dividends>
</companies>
<companies>
    <code>MPCCEL</code>
    <security>MPC CARIBBEAN CLEAN ENERGY LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>21666542</outstandingShares>
    <marketCapitalization>2166654200</marketCapitalization>
</companies>
<companies>
    <code>NCBFG</code>
    <security>NCB FINANCIAL GROUP LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>2466762828</outstandingShares>
    <marketCapitalization>293560618082.88</marketCapitalization>
    <dividends>
        <code>NCBFG</code>
        <recordDate>2021-05-14</recordDate>
        <paymentDate>2021-05-31</paymentDate>
        <currency>JMD</currency>
        <amount>0.5</amount>
    </dividends>
</companies>
<companies>
    <code>PAL</code>
    <security>PALACE AMUSEMENT CO. LTD.</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1437028</outstandingShares>
    <marketCapitalization>1480138840</marketCapitalization>
</companies>
<companies>
    <code>PJAM</code>
    <security>PANJAM INVESTMENT LIMITED</security>
    <currency>JMD</currency>
    <industry>CONGLOMERATES</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1066159890</outstandingShares>
    <marketCapitalization>71518371114.04</marketCapitalization>
    <dividends>
        <code>PJAM</code>
        <recordDate>2022-01-04</recordDate>
        <paymentDate>2022-01-19</paymentDate>
        <currency>JMD</currency>
        <amount>0.285</amount>
    </dividends>
    <dividends>
        <code>PJAM</code>
        <recordDate>2021-11-29</recordDate>
        <paymentDate>2021-12-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.26</amount>
    </dividends>
    <dividends>
        <code>PJAM</code>
        <recordDate>2021-08-26</recordDate>
        <paymentDate>2021-09-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.2</amount>
    </dividends>
    <dividends>
        <code>PJAM</code>
        <recordDate>2021-05-28</recordDate>
        <paymentDate>2021-06-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.15</amount>
    </dividends>
    <dividends>
        <code>PJAM</code>
        <recordDate>2021-03-17</recordDate>
        <paymentDate>2021-03-31</paymentDate>
        <currency>JMD</currency>
        <amount>0.105</amount>
    </dividends>
    <dividends>
        <code>PJAM</code>
        <recordDate>2020-11-27</recordDate>
        <paymentDate>2020-12-17</paymentDate>
        <currency>JMD</currency>
        <amount>0.105</amount>
    </dividends>
</companies>
<companies>
    <code>PJX</code>
    <security>PORTLAND JSX LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>309968261</outstandingShares>
    <marketCapitalization>2746318792.46</marketCapitalization>
</companies>
<companies>
    <code>PBS9.75</code>
    <security>PRODUCTIVE BUSINESS SOLUTIONS LTD 9.75% CUMULATIVE REDEEMABLE</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>25800000</outstandingShares>
    <marketCapitalization>2709000000</marketCapitalization>
</companies>
<companies>
    <code>PROVEN</code>
    <security>PROVEN INVESTMENTS LIMITED JMD</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>759432000</outstandingShares>
    <marketCapitalization>27005780117.14</marketCapitalization>
</companies>
<companies>
    <code>PULS</code>
    <security>PULSE INVESTMENTS LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>6522952176</outstandingShares>
    <marketCapitalization>25161211731.81</marketCapitalization>
    <dividends>
        <code>PULS</code>
        <recordDate>2021-03-05</recordDate>
        <paymentDate>2021-04-07</paymentDate>
        <currency>JMD</currency>
        <amount>0.005</amount>
    </dividends>
</companies>
<companies>
    <code>QWI</code>
    <security>QWI INVESTMENTS LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1365000015</outstandingShares>
    <marketCapitalization>1362850139.98</marketCapitalization>
</companies>
<companies>
    <code>RJR</code>
    <security>RADIO JAMAICA LIMITED</security>
    <currency>JMD</currency>
    <industry>COMMUNICATIONS</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>2422487654</outstandingShares>
    <marketCapitalization>6711254951.67</marketCapitalization>
    <dividends>
        <code>RJR</code>
        <recordDate>2021-09-21</recordDate>
        <paymentDate>2021-10-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.02</amount>
    </dividends>
</companies>
<companies>
    <code>SJ</code>
    <security>SAGICOR GROUP JAMAICA LIMITED</security>
    <currency>JMD</currency>
    <industry>CONGLOMERATES</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>3905634918</outstandingShares>
    <marketCapitalization>234077300213.99</marketCapitalization>
    <dividends>
        <code>SJ</code>
        <recordDate>2021-10-27</recordDate>
        <paymentDate>2021-11-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.4966</amount>
    </dividends>
    <dividends>
        <code>SJ</code>
        <recordDate>2021-04-26</recordDate>
        <paymentDate>2021-05-14</paymentDate>
        <currency>JMD</currency>
        <amount>0.6124</amount>
    </dividends>
    <dividends>
        <code>SJ</code>
        <recordDate>2020-10-28</recordDate>
        <paymentDate>2020-11-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.4461</amount>
    </dividends>
</companies>
<companies>
    <code>XFUND</code>
    <security>SAGICOR REAL ESTATE X FUND LTD.</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>2243005125</outstandingShares>
    <marketCapitalization>18760277294</marketCapitalization>
</companies>
<companies>
    <code>SELECTF</code>
    <security>SAGICOR SELECT FUNDS LIMITED - FINANCIAL</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>5100000000</outstandingShares>
    <marketCapitalization>2619905700</marketCapitalization>
    <dividends>
        <code>SELECTF</code>
        <recordDate>2021-11-25</recordDate>
        <paymentDate>2021-12-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.0114</amount>
    </dividends>
    <dividends>
        <code>SELECTF</code>
        <recordDate>2021-05-26</recordDate>
        <paymentDate>2021-07-02</paymentDate>
        <currency>JMD</currency>
        <amount>0.0056</amount>
    </dividends>
</companies>
<companies>
    <code>SELECTMD</code>
    <security>SAGICOR SELECT FUNDS LIMITED MANUFACTURING &amp; DISTRIBUTION</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>3816612000</outstandingShares>
    <marketCapitalization>2748006439.34</marketCapitalization>
    <dividends>
        <code>SELECTMD</code>
        <recordDate>2021-11-25</recordDate>
        <paymentDate>2021-12-16</paymentDate>
        <currency>JMD</currency>
        <amount>0.0077</amount>
    </dividends>
    <dividends>
        <code>SELECTMD</code>
        <recordDate>2021-05-26</recordDate>
        <paymentDate>2021-07-02</paymentDate>
        <currency>JMD</currency>
        <amount>0.0105</amount>
    </dividends>
</companies>
<companies>
    <code>SALF</code>
    <security>SALADA FOODS JAMAICA LTD.</security>
    <currency>JMD</currency>
    <industry>MANUFACTURING</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1038832900</outstandingShares>
    <marketCapitalization>6793716807.27</marketCapitalization>
    <dividends>
        <code>SALF</code>
        <recordDate>2021-12-03</recordDate>
        <paymentDate>2021-12-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.055</amount>
    </dividends>
    <dividends>
        <code>SALF</code>
        <recordDate>2021-06-07</recordDate>
        <paymentDate>2021-06-25</paymentDate>
        <currency>JMD</currency>
        <amount>0.054</amount>
    </dividends>
    <dividends>
        <code>SALF</code>
        <recordDate>2020-12-04</recordDate>
        <paymentDate>2020-12-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.5</amount>
    </dividends>
</companies>
<companies>
    <code>SGJ</code>
    <security>SCOTIA GROUP JAMAICA LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>3111572984</outstandingShares>
    <marketCapitalization>107502086631.96</marketCapitalization>
    <dividends>
        <code>SGJ</code>
        <recordDate>2021-12-30</recordDate>
        <paymentDate>2022-01-21</paymentDate>
        <currency>JMD</currency>
        <amount>0.35</amount>
    </dividends>
    <dividends>
        <code>SGJ</code>
        <recordDate>2021-09-28</recordDate>
        <paymentDate>2021-10-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.35</amount>
    </dividends>
    <dividends>
        <code>SGJ</code>
        <recordDate>2021-06-29</recordDate>
        <paymentDate>2021-07-21</paymentDate>
        <currency>JMD</currency>
        <amount>0.35</amount>
    </dividends>
    <dividends>
        <code>SGJ</code>
        <recordDate>2021-03-31</recordDate>
        <paymentDate>2021-04-22</paymentDate>
        <currency>JMD</currency>
        <amount>0.4</amount>
    </dividends>
    <dividends>
        <code>SGJ</code>
        <recordDate>2020-12-29</recordDate>
        <paymentDate>2021-01-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.45</amount>
    </dividends>
    <dividends>
        <code>SGJ</code>
        <recordDate>2020-09-29</recordDate>
        <paymentDate>2020-10-21</paymentDate>
        <currency>JMD</currency>
        <amount>0.1</amount>
    </dividends>
</companies>
<companies>
    <code>SEP</code>
    <security>SEPROD LIMITED</security>
    <currency>JMD</currency>
    <industry>MANUFACTURING</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>733546855</outstandingShares>
    <marketCapitalization>42500197339.91</marketCapitalization>
    <dividends>
        <code>SEP</code>
        <recordDate>2021-11-26</recordDate>
        <paymentDate>2021-12-10</paymentDate>
        <currency>JMD</currency>
        <amount>0.5</amount>
    </dividends>
    <dividends>
        <code>SEP</code>
        <recordDate>2021-08-12</recordDate>
        <paymentDate>2021-08-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.5</amount>
    </dividends>
    <dividends>
        <code>SEP</code>
        <recordDate>2021-03-10</recordDate>
        <paymentDate>2021-03-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.3</amount>
    </dividends>
    <dividends>
        <code>SEP</code>
        <recordDate>2020-09-30</recordDate>
        <paymentDate>2020-10-19</paymentDate>
        <currency>JMD</currency>
        <amount>0.3</amount>
    </dividends>
</companies>
<companies>
    <code>SML</code>
    <security>STANLEY MOTTA LIMITED ORDINARY SHARES</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>757828490</outstandingShares>
    <marketCapitalization>4323083395.71</marketCapitalization>
    <dividends>
        <code>SML</code>
        <recordDate>2021-11-22</recordDate>
        <paymentDate>2021-12-06</paymentDate>
        <currency>JMD</currency>
        <amount>0.066</amount>
    </dividends>
    <dividends>
        <code>SML</code>
        <recordDate>2021-08-23</recordDate>
        <paymentDate>2021-09-06</paymentDate>
        <currency>JMD</currency>
        <amount>0.092</amount>
    </dividends>
    <dividends>
        <code>SML</code>
        <recordDate>2021-03-26</recordDate>
        <paymentDate>2021-04-23</paymentDate>
        <currency>JMD</currency>
        <amount>0.092</amount>
    </dividends>
    <dividends>
        <code>SML</code>
        <recordDate>2020-11-23</recordDate>
        <paymentDate>2020-12-07</paymentDate>
        <currency>JMD</currency>
        <amount>0.13</amount>
    </dividends>
</companies>
<companies>
    <code>SIL</code>
    <security>STERLING INVESTMENTS LIMITED</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>418731205</outstandingShares>
    <marketCapitalization>1231383791.1</marketCapitalization>
    <dividends>
        <code>SIL</code>
        <recordDate>2022-03-04</recordDate>
        <paymentDate>2022-03-17</paymentDate>
        <currency>USD</currency>
        <amount>0.0005</amount>
    </dividends>
    <dividends>
        <code>SIL</code>
        <recordDate>2021-08-27</recordDate>
        <paymentDate>2021-09-13</paymentDate>
        <currency>USD</currency>
        <amount>0.0006</amount>
    </dividends>
</companies>
<companies>
    <code>SVL</code>
    <security>SUPREME VENTURES LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>2637254926</outstandingShares>
    <marketCapitalization>47839841279.21</marketCapitalization>
    <dividends>
        <code>SVL</code>
        <recordDate>2021-11-04</recordDate>
        <paymentDate>2021-11-18</paymentDate>
        <currency>JMD</currency>
        <amount>0.11</amount>
    </dividends>
    <dividends>
        <code>SVL</code>
        <recordDate>2021-08-10</recordDate>
        <paymentDate>2021-08-24</paymentDate>
        <currency>JMD</currency>
        <amount>0.21</amount>
    </dividends>
    <dividends>
        <code>SVL</code>
        <recordDate>2021-05-07</recordDate>
        <paymentDate>2021-05-21</paymentDate>
        <currency>JMD</currency>
        <amount>0.2</amount>
    </dividends>
    <dividends>
        <code>SVL</code>
        <recordDate>2021-03-15</recordDate>
        <paymentDate>2021-03-23</paymentDate>
        <currency>JMD</currency>
        <amount>0.28</amount>
    </dividends>
    <dividends>
        <code>SVL</code>
        <recordDate>2020-11-16</recordDate>
        <paymentDate>2020-12-04</paymentDate>
        <currency>JMD</currency>
        <amount>0.2</amount>
    </dividends>
</companies>
<companies>
    <code>SCIUSD</code>
    <security>SYGNUS CREDIT INVESTMENTS LIMITED JMD ORDINARY SHARES</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>242735763</outstandingShares>
    <marketCapitalization>3170129064.78</marketCapitalization>
    <dividends>
        <code>SCIUSD</code>
        <recordDate>2021-09-30</recordDate>
        <paymentDate>2021-10-15</paymentDate>
        <currency>USD</currency>
        <amount>0.0026</amount>
    </dividends>
    <dividends>
        <code>SCIUSD</code>
        <recordDate>2021-03-15</recordDate>
        <paymentDate>2021-04-01</paymentDate>
        <currency>USD</currency>
        <amount>0.0015</amount>
    </dividends>
</companies>
<companies>
    <code>SCIJMD</code>
    <security>SYGNUS CREDIT INVESTMENTS LIMITED JMD ORDINARY SHARES</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>0</outstandingShares>
    <marketCapitalization>0</marketCapitalization>
</companies>
<companies>
    <code>SRFJMD</code>
    <security>SYGNUS REAL ESTATE FINANCIAL LIMITED (JMD)</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>187392532</outstandingShares>
    <marketCapitalization>3125707433.76</marketCapitalization>
</companies>
<companies>
    <code>TJH</code>
    <security>TRANSJAMAICAN HIGHWAY LIMITED</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>12501000000</outstandingShares>
    <marketCapitalization>15397831728</marketCapitalization>
    <dividends>
        <code>TJH</code>
        <recordDate>2021-12-03</recordDate>
        <paymentDate>2021-12-20</paymentDate>
        <currency>JMD</currency>
        <amount>0.0865</amount>
    </dividends>
    <dividends>
        <code>TJH</code>
        <recordDate>2020-11-30</recordDate>
        <paymentDate>2020-12-15</paymentDate>
        <currency>JMD</currency>
        <amount>0.0748</amount>
    </dividends>
</companies>
<companies>
    <code>TJH8.0</code>
    <security>TRANSJAMAICAN HIGHWAY LTD 8%</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>PREFERENCE</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>2700000000</outstandingShares>
    <marketCapitalization>4347000000</marketCapitalization>
</companies>
<companies>
    <code>VMIL</code>
    <security>VICTORIA MUTUAL INVESTMENTS LTD ORDINARY SHARES</security>
    <currency>JMD</currency>
    <industry>FINANCE</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>1500025000</outstandingShares>
    <marketCapitalization>10130621340.88</marketCapitalization>
    <dividends>
        <code>VMIL</code>
        <recordDate>2021-11-26</recordDate>
        <paymentDate>2021-12-10</paymentDate>
        <currency>JMD</currency>
        <amount>0.155</amount>
    </dividends>
</companies>
<companies>
    <code>WIG</code>
    <security>WIGTON WINDFARM LIMITED ORDINARY SHARES</security>
    <currency>JMD</currency>
    <industry>OTHER</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>11000000000</outstandingShares>
    <marketCapitalization>5743221000</marketCapitalization>
    <dividends>
        <code>WIG</code>
        <recordDate>2021-12-29</recordDate>
        <paymentDate>2022-01-17</paymentDate>
        <currency>JMD</currency>
        <amount>0.0182</amount>
    </dividends>
</companies>
<companies>
    <code>WISYNCO</code>
    <security>WISYNCO GROUP LTD ORDINARY SHARES</security>
    <currency>JMD</currency>
    <industry>MANUFACTURING</industry>
    <type>ORDINARY</type>
    <listed>true</listed>
    <date>2022-03-10</date>
    <outstandingShares>3756250000</outstandingShares>
    <marketCapitalization>73187898118.75</marketCapitalization>
    <dividends>
        <code>WISYNCO</code>
        <recordDate>2022-02-15</recordDate>
        <paymentDate>2022-03-01</paymentDate>
        <currency>JMD</currency>
        <amount>0.2</amount>
    </dividends>
    <dividends>
        <code>WISYNCO</code>
        <recordDate>2021-07-15</recordDate>
        <paymentDate>2021-08-05</paymentDate>
        <currency>JMD</currency>
        <amount>0.2</amount>
    </dividends>
    <dividends>
        <code>WISYNCO</code>
        <recordDate>2021-02-11</recordDate>
        <paymentDate>2021-02-25</paymentDate>
        <currency>JMD</currency>
        <amount>0.1</amount>
    </dividends>
</companies>';


EXEC [dbo].[UpdateCompaniesDetails] @dividends;