USE [master]
GO
/****** Object:  Database [stocks]    Script Date: 18/1/2021 7:58:34 am ******/
CREATE DATABASE [stocks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'stocks', FILENAME = N'/var/opt/mssql/data/stocks.mdf', MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'stocks_log', FILENAME = N'/var/opt/mssql/data/stocks_log.ldf', MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [stocks] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [stocks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [stocks] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [stocks] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [stocks] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [stocks] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [stocks] SET ARITHABORT OFF 
GO
ALTER DATABASE [stocks] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [stocks] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [stocks] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [stocks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [stocks] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [stocks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [stocks] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [stocks] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [stocks] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [stocks] SET  DISABLE_BROKER 
GO
ALTER DATABASE [stocks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [stocks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [stocks] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [stocks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [stocks] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [stocks] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [stocks] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [stocks] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [stocks] SET  MULTI_USER 
GO
ALTER DATABASE [stocks] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [stocks] SET DB_CHAINING OFF 
GO
ALTER DATABASE [stocks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [stocks] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [stocks] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [stocks] SET QUERY_STORE = OFF
GO